name: pub_api_client
description: An API Client for Pub to interact with public package information.
version: 2.0.0
homepage: https://github.com/leoafarias/pub_api_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  
  freezed_annotation: ^0.14.1
  http: ^0.13.1
  json_annotation: ^4.0.1
  pub_semver: ^2.0.0
  pubspec: ^2.0.1
  pubspec_parse: ^1.0.0
  
dev_dependencies:
  build_runner: ^1.12.2
  build_version: ^2.0.2
  freezed: ^0.14.1+1
  json_serializable: ^4.1.0
  pedantic: ^1.11.0
  test: ^1.16.8
  # test_coverage: ^0.5.0
