name: Build Static API

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  build-static:
    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
        # Grind task to build static files
      - name: Activate Grinder
        run: pub global activate grinder
      - name: Build static files
        run: pub run grinder
        # Store static files
      - name: Save static files for storage
        uses: sylvanld/action-storage@v1
        with:
          src: static/google_deps.json
          dst: static
